swagger: '2.0'
info:
  title: Open Banking Authorization - Access Token Management
  version: 1.0.0
  description: >-
    Esta Api se encarga de generar un token de acceso al TPP para autenticarse
    en nuestros recursos  a partir del client_assertion, adicional permite
    generar  el intercambio del código de autorizacion (generado cuando el
    cliente se autentica en la experiencia del banco)  por un token de acceso y
    si este token de acceso se vence, se genera un nuevo token de acceso a
    partir del codigo de autorizacion vigente.
  x-ibm-name: open-banking-authorization-access-token-management
paths:
  /token:
    post:
      operationId: AccessTokenManagement
      x-api-type: traditional
      summary: >-
        La operacion permite  realizar la  creacion del token de acceso una vez
        el  TPP envía las credenciales de la aplicación al servidor de
        autorización (private_key_jwt). Con este token generado se puede
        utilizar  para llamar a un recurso en su nombre, siempre y cuando esté
        autorizada por el scope asociado al token. Adicional, permite
        intercambiar el código de autorización generado durante el proceso de
        autorización por un token de acceso y permite realizar la actualizacion
        o refresh del token de acceso
      description: '### Clasificación de la información: Interno'
      parameters:
        - name: content-type
          in: header
          required: true
          type: string
          description: >-
            'Indica el formato de mensajería que es enviado hacia la API, el
            cual debe ser application/x-www-form-urlencoded.'
        - name: accept
          in: header
          required: false
          type: string
          description: >-
            Indica el formato de mensajería que es aceptado como respuesta de la
            API (application/json)
        - name: grant_type
          in: formData
          required: true
          type: string
          minLength: 1
          maxLength: 20
          enum:
            - authorization_code
            - refresh_token
            - 'client_credentials '
          description: >-
            Método a través del cual la aplicacion puede obtener tokens de
            acceso. Ejemplo: "authorization_code"
        - name: scope
          in: formData
          required: true
          type: string
          minLength: 1
          maxLength: 128
          enum:
            - payment
            - account
            - 'openid '
          description: >-
            Alcance del token generado. Este campo es obligatorio para todos los
            valores del campo grant_type. Ejemplo: "payment"    
        - name: code
          in: formData
          required: false
          type: string
          minLength: 1
          maxLength: 256
          description: >-
            Código de autorizacion que se intercambia por el token de acceso 
            Para este campo la obligatoriedad depénde del valor del campo
            grant_type, cuando sea Authorization_code es obligatorio. Ejemplo:
            "vRZs_yPSuzsap3BIW9w7CmzgEgJ3MFCsLVkAAAAE"
        - name: code_verifier
          in: formData
          required: false
          type: string
          minLength: 1
          maxLength: 512
          description: >-
            Código para verificar que el cliente que genero el código de
            autorización es el mismo que esta intentando intercambiarlo por un
            token de acceso. Para este campo la obligatoriedad depénde del valor
            del campo grant_type, cuando sea Authorization_code es obligatorio.
            Ejemplo: "RczZn-l7WMCUIiKQLNcWBXHVNfb1_IR25rGwY1nNAt8"
              
        - name: client_assertion_type
          in: formData
          required: true
          type: string
          minLength: 1
          maxLength: 64
          description: >-
            Define el formato del jwt que usara la aplicación consumidora para
            autenticarse. Se usa para habilitar la autenticación mediante
            private_key_jwt.Este campo es obligatorio para todos los valores del
            grant_type. Ejemplo:
            "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
              
        - name: client_assertion
          in: formData
          required: true
          type: string
          minLength: 1
          maxLength: 1024
          description: >-
            Contiene el JWT usado para autenticar la aplicación consumidora en
            el servidor de autorización mediante private_key_jwt. Este campo es
            obligatorio para todos los valores del grant_type. Ejemplo: "UN
            PrivateKeyJWT" 
              
        - name: client_id
          in: formData
          required: false
          type: string
          minLength: 1
          maxLength: 512
          description: >-
            Identificador emitido para el cliente por el servidor de
            autorización. Este es opcional para todos los valores del
            grant_type. Ejemplo: "7xPKBspndegEsfR2f2Fss2s"
        - name: redirect_uri
          in: formData
          required: false
          type: string
          minLength: 1
          maxLength: 1024
          description: >-
            Se utiliza para especificar el URI al que se redirigirá al usuario
            después de haber validado los permisos solicitados por el cliente
            (TPP). Debe ser un URI válido que esté registrado en el servidor de
            autorización.  Para este campo la obligatoriedad depénde del valor
            del campo grant_type cuando sea authorization_code es obligatorio.
            Ejemplo: https://developer.natwest.com/dummy_redirect.htm
        - name: refresh_token
          in: formData
          required: false
          type: string
          minLength: 1
          maxLength: 1024
          description: >-
            Token de refresco que se utiliza para generar un nuevo access token 
            valor del campo grant_type cuando sea Refresh_token es obligatorio.
            Ejemplo:
            "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"   
      responses:
        '200':
          x-success-response: Successfull
          schema:
            $ref: '#/definitions/AccessTokenManagementResponse'
          description: Respuesta exitosa
          x-ibm-languages:
            description:
              en: Successful response.
          headers:
            content-type:
              type: string
              description: >-
                'Indica el formato de mensajería que es enviado hacia la API 
                Ejemplo: application/x-www-form-urlencoded.'
            content-length:
              type: string
              description: >-
                Indica el tamaño del cuerpo del mensaje, en bytes, enviado al
                destinatario
            date:
              type: string
              description: 'Fecha de creacion del token       '
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '500':
          $ref: '#/responses/500'
      security:
        - clientSecret: []
          clientId: []
  /access-token-management/health:
    head:
      operationId: healthOperation
      responses:
        '200':
          description: Respuesta exitosa.
          x-ibm-languages:
            description:
              en: Successful response.
      security:
        - clientId: []
          clientSecret: []
      tags:
        - Monitoring
responses:
  '400':
    schema:
      $ref: '#/definitions/failure'
    description: Error en la solicitud.
    x-ibm-languages:
      description:
        en: Error in the request.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 400
        Message: Bad Resquest
        Errors:
          - ErrorCode: SA400
            Detail: Número de página no proporcionado.
    headers:
      content-type:
        type: string
        description: >-
          'Indica el formato de mensajería que es enviado hacia la API  Ejemplo:
          application/x-www-form-urlencoded.'
      content-length:
        type: string
        description: >-
          Indica el tamaño del cuerpo del mensaje, en bytes, enviado al
          destinatario
      date:
        type: string
        description: Fecha de creacion del token
  '401':
    schema:
      $ref: '#/definitions/failure'
    description: Credenciales incorrectas.
    x-ibm-languages:
      description:
        en: Incorrect credentials.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 401
        Message: Unauthorized
        Errors:
          - ErrorCode: SA401
            Detail: Consulta no autorizada por el usuario.
    headers:
      content-type:
        type: string
        description: >-
          'Indica el formato de mensajería que es enviado hacia la API  Ejemplo:
          application/x-www-form-urlencoded.'
      content-length:
        type: string
        description: >-
          Indica el tamaño del cuerpo del mensaje, en bytes, enviado al
          destinatario
      date:
        type: string
        description: 'Fecha de creacion del token            '
  '500':
    schema:
      $ref: '#/definitions/failure'
    description: Error interno del servidor.
    x-ibm-languages:
      description:
        en: Internal server error.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 500
        Message: Internal Server Error
        Errors:
          - ErrorCode: SP500
            Detail: Ha ocurrido un error interno controlado en el servidor.
    headers:
      content-type:
        type: string
        description: >-
          'Indica el formato de mensajería que es enviado hacia la API  Ejemplo:
          application/x-www-form-urlencoded.'
      content-length:
        type: string
        description: >-
          Indica el tamaño del cuerpo del mensaje, en bytes, enviado al
          destinatario
      date:
        type: string
        description: 'Fecha de creacion del token            '
definitions:
  AccessTokenManagementResponse:
    required:
      - access_token
      - scope
      - token_type
      - expires_in
    properties:
      access_token:
        type: string
        description: 'token de acceso generado que sirve para el acceso a los recursos '
        minLength: 1
        maxLength: 1024
        example: zlJojElfSalTBc1CKVwi3adSHPpr
      refresh_token:
        type: string
        description: >-
          Token de refresco que se puede utilizar para generar un nuevo access
          token Para este campo la obligatoriedad depénde del valor del campo
          scope cuando sea account es obligatorio 
        minLength: 1
        maxLength: 1024
        example: EhRx3DsdmpU4J8ISVBeVYj5v5l2I2oDorfEVgbPcft
      scope:
        type: string
        description: Alcance del consentimiento generado.
        enum:
          - Payment
          - Account
          - Openid
        minLength: 1
        maxLength: 128
        example: Payment
      id_token:
        type: string
        description: >-
          Token de acceso que contiene la informacion del usuario, se conoce
          como token OpenId Connect. Es un JWT. Los campos  minimos son: iss sub
          aud exp iat auth_time (este último es opcional). Para este campo la
          obligatoriedad depénde del valor del campo grant_type cuando sea
          authorization_code es obligatorio
        minLength: 1
        maxLength: 2048
        example: >-
          yJhbGciOiJSUzI1NiIsImtpZCI6Ikg4OVBtWGx0VXVlVmFLLS1uVlNZM2c2SlBxYyJ9.eyJzdWIiOiJjMjE1OGIwMDIxZWQ0MmJiYjY0ZWUxY2MyZTUzNDc0MSIsImF1ZCI6IjZ4UFVIeG1TbU44bGZMMkZienV4M3MiLCJqdGkiOiJkdmZoUXhlV3ZxNzZnc082OXhLRjcwIiwiaXNzIjoiaHR0cHM6Ly9pYW0tYXV0aG4tc2l0LW53Yi5tYW5hZ2VkdGVzdC5jb20iLCJpYXQiOjE1NDIwMTY0NzgsImV4cCI6MTU0MjAxNjc3OCwib3BlbmJhbmtpbmdfaW50ZW50X2lkIjoiYzIxNThiMDAyMWVkNDJiYmI2NGVlMWNjMmU1MzQ3NDEiLCJub25jZSI6IjllZGNjMTdiLThkMTMtNGI4My04M2VhLTNkZWIxMDQ4ZTM0NCIsImF1dGhfdGltZSI6MTU0MjAxNjQ3OCwiY19oYXNoIjoiazB1QlhqbF9pdF9tT2JvRE5wSTR1USIsInNfaGFzaCI6IjZjN25Hcmt5X2Voak00MEl2azNwM3cifQ.AycZlfTkTuHhEW_7GyWU_h12XszrNzs4Z47tPA9xPRcjpPG-ret7oNhi1pMlO2uiC7VcXPd_uwg_6V7KbKEj8CkpZ3IRibAMgF12OhNUaYRL8Kboopic9JpvU4SH0wgR4_SfixusjQYm2a7MsT11FFA7vvzZzKDh0mW8NRkin3tZ4PWoD-4NAuO8OFHtQ5ZTCSNqwASXdQlUyuiNYW1xq26irLhmD5E4u6g02urcKB5BCGsqEByVddYlqNB2TwNyJBz3kW033X__icIWEe9isJHqtXhe-7y2wrEHVLwDVTZzN2Z5dXPVJB82JEsXl_qeVTdpDJNdZB7n1HeIIBB6jA
      token_type:
        type: string
        description: Tipo de token generado
        minLength: 1
        maxLength: 6
        example: Bearer
      expires_in:
        type: number
        description: Tiempo de expiracion del token generado
        minLength: 1
        maxLength: 10
        example: '599'
  failure:
    type: object
    description: Mensaje de respuesta cuando ocurre un error.
    required:
      - Code
      - Message
    properties:
      Code:
        type: number
        description: >-
          Codigo de estado HTTP (status code) asociado al mensaje de error de la
          respuesta del llamado a la API.
        example: 404
      Message:
        type: string
        description: >-
          Titulo asociado al codigo de estado HTTP (status code) asociado al
          mensaje de error de la respuesta del llamado a la API.
        example: Not Found
      Errors:
        type: array
        description: Lista de errores detectados
        items:
          $ref: '#/definitions/error'
  error:
    type: object
    required:
      - ErrorCode
      - Detail
    properties:
      ErrorCode:
        description: An application-specific error code, expressed as a string value.
        type: string
        example: BP404
      Detail:
        description: >-
          A human-readable explanation specific to this occurrence of the
          problem.
        type: string
        example: Requested resource could not be found
schemes:
  - https
consumes:
  - application/x-www-form-urlencoded
host: gw-baas-dev.apps.ambientesbc.lab/public-partner/testing
produces:
  - application/json
securityDefinitions:
  clientId:
    type: apiKey
    in: header
    name: Client-Id
    x-key-type: client_id
  clientSecret:
    type: apiKey
    in: header
    name: Client-Secret
    x-key-type: client_secret
tags:
  - name: Monitoring
    description: Operaciones para realizar el monitoreo de la API
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  phase: realized
  catalogs:
    Development:
      properties:
        catalogName: development
        profileTls: ''
        endpoint: https://esbdev.bancolombia.corp:3300/ESB/SOAP/Default
    Production:
      properties:
        catalogName: production
        profileTls: ''
        endpoint: https://esbpro.bancolombia.corp:3300/ESB/SOAP/Default
    Testing:
      properties:
        catalogName: testing
        profileTls: ''
        endpoint: https://esbqa.bancolombia.corp:3300/ESB/SOAP/Default
    Sandbox:
      properties:
        catalogName: sandbox
        profileTls: apic-tls-profile-cluster-eks-integracion-sandbox:1.0.0
        endpoint: https://integracion-int-qa.apps.ambientesbc.lab/
  type: rest
x-API-Protocol:
  Protocols: HTTPS
basePath: public-partner/testingundefined
