swagger: '2.0'
info:
  title: Account Information - Account Access Consents
  version: 1.0.0
  description: >-
    Permite a los terceros, en un modelo open banking, solicitar la creación de
    un recurso de consentimiento de acceso a información de cuentas Bancolombia,
    así como consultar el estado del mismo.
  x-ibm-name: account-information-account-access-consents
basePath: public-partner/testing/open-banking/v1/deposits
paths:
  /accounts/account-access-consent:
    post:
      operationId: AccountAccessConsent
      x-api-type: traditional
      summary: >-
        Crea un recurso de consentimiento de acceso a información de cuentas
        Bancolombia.
      description: >-
        ### Clasificación de la información: Confidencial

        Crea un recurso de consentimiento con el fin de otorgar permisos
        relacionados a información de las cuentas.
      parameters:
        - name: authorization
          in: header
          required: true
          type: string
          description: Token de autorización tipo Bearer como lo indica la RFC 6750.
        - name: accept
          in: header
          required: false
          type: string
          description: >-
            Indica el formato de mensajería que es aceptado como respuesta de la
            API (application/json).
        - name: content-type
          in: header
          required: true
          type: string
          description: >-
            Indica el formato de mensajería que es enviado hacia la API
            (application/json).        
        - name: requestBody
          in: body
          required: true
          schema:
            $ref: '#/definitions/AccountAccessConsentRequest'
      responses:
        '201':
          x-success-response: Successfull
          schema:
            $ref: '#/definitions/AccountAccessConsentResponse'
          description: Respuesta exitosa
          x-ibm-languages:
            description:
              en: Successful response.
          headers:
            content-type:
              type: string
              description: >-
                Indica el formato de mensajería que es aceptado como respuesta
                de la API (application/json)
              x-ibm-languages:
                description:
                  en: >-
                    API message format. Example:
                    application/vnd.bancolombia.v4+json.
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
      security:
        - clientSecret: []
          clientId: []
      tags:
        - Account Access Consents
  /accounts/account-access-consent/{consentId}:
    get:
      operationId: RetrieveAccountAccessConsent
      x-api-type: traditional
      summary: Consultar recurso de consentimiento de acceso a información de cuentas.
      description: >-
        ### Clasificación de la información: Confidencial

        Permite consultar un recurso de consentimiento de acceso a información
        de cuentas para comprobar su estado.
      parameters:
        - name: authorization
          in: header
          required: true
          type: string
          description: Token de autorización tipo Bearer como lo indica la RFC 6750.
        - name: consentId
          in: path
          required: true
          type: string
          description: Identificador creado para el recurso de consentimiento.
        - name: accept
          in: header
          required: false
          type: string
          description: >-
            Indica el formato de mensajería que es aceptado como respuesta de la
            API (application/json).
      responses:
        '200':
          x-success-response: Successfull
          schema:
            $ref: '#/definitions/RetrieveAccountAccessConsentResponse'
          description: Respuesta exitosa
          x-ibm-languages:
            description:
              en: Successful response.
          headers:
            content-type:
              type: string
              description: >-
                Indica el formato de mensajería que es aceptado como respuesta
                de la API (application/json)
              x-ibm-languages:
                description:
                  en: >-
                    API message format. Example:
                    application/vnd.bancolombia.v4+json.
        '401':
          $ref: '#/responses/401'
        '404':
          $ref: '#/responses/404'
      security:
        - clientSecret: []
          clientId: []
      tags:
        - Account Access Consents
  /health:
    head:
      operationId: healthOperation
      responses:
        '200':
          description: Respuesta exitosa.
          x-ibm-languages:
            description:
              en: Successful response.
      security:
        - clientId: []
          clientSecret: []
      tags:
        - Monitoring
responses:
  '400':
    schema:
      $ref: '#/definitions/failure'
    description: Error en la solicitud.
    x-ibm-languages:
      description:
        en: Error in the request.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 400
        Message: Bad Resquest
        Errors:
          - ErrorCode: BP4001
            Detail: No se especifican los permisos en la solicitud.
    headers:
      content-type:
        type: string
        description: >-
          Indica el formato de mensajería que es aceptado como respuesta de la
          API (application/json)
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/vnd.bancolombia.v4+json.'
  '401':
    schema:
      $ref: '#/definitions/failure'
    description: Credenciales incorrectas.
    x-ibm-languages:
      description:
        en: Incorrect credentials.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 401
        Message: Unauthorized
        Errors:
          - ErrorCode: SA401
            Detail: Tercero no autorizado.
    headers:
      content-type:
        type: string
        description: >-
          Indica el formato de mensajería que es aceptado como respuesta de la
          API (application/json)
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/vnd.bancolombia.v4+json.'
  '404':
    schema:
      $ref: '#/definitions/failure'
    description: Recurso no encontrado.
    x-ibm-languages:
      description:
        en: Resource not found.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 404
        Message: Not Found
        Errors:
          - ErrorCode: BP4041
            Detail: Consentimiento no existe.
    headers:
      content-type:
        type: string
        description: >-
          Indica el formato de mensajería que es aceptado como respuesta de la
          API (application/json)
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/vnd.bancolombia.v4+json.'
definitions:
  AccountAccessConsentResponse:
    type: object
    required:
      - Data
    properties:
      Data:
        type: object
        required:
          - ConsentId
          - Permissions
          - CreationDateTime
          - ExpirationDateTime
          - Status
        properties:
          ConsentId:
            type: string
            description: Identificador creado para el recurso de consentimiento.
            minLength: 1
            maxLength: 128
            example: f236b014ebb845ccal275d638mha5684
          Permissions:
            type: array
            description: >-
              Arreglo que contiene los permisos específicos solicitados por el
              tercero.
            example:
              - ReadAccountBasic
            items:
              type: string
              minLength: 1
              maxLength: 40
          CreationDateTime:
            type: string
            format: date-time
            description: Fecha de creación del recurso de consentimiento.
          ExpirationDateTime:
            type: string
            format: date-time
            description: >-
              Fecha y hora de expiración para el permiso solicitado. Se
              contemplan 3 vigencias para el consentimiento: durante 3 meses,
              durante 6 meses y durante 1 año. Si no se envía, tomará el valor
              máximo.
          TransactionFromDateTime:
            type: string
            format: date-time
            description: >-
              Fecha desde la cual se solicita listar las transacciones (si el
              permiso solicitado aplica). Si no se envía se solicitarán
              transacciones por el máximo tiempo permitido (90 días) o lo que
              exista en el sistema.
          TransactionToDateTime:
            type: string
            format: date-time
            description: >-
              Fecha hasta la cual se solicita listar las transacciones (si el
              permiso solicitado aplica). Si no se envía se solicitará hasta la
              última transacción disponible.
          Status:
            type: string
            description: >-
              Estado actual del recurso de consentimiento. Al ser un recurso
              nuevo se creará bajo el estado AwaitingAuthorization.
            minLength: 7
            maxLength: 21
            example: AwaitingAuthorization
          StatusUpdateDateTime:
            type: string
            format: date-time
            description: >-
              Fecha en la cual el recurso de consentimiento pasó a tomar el
              estado actual.
      Links:
        $ref: '#/definitions/Links'
  Links:
    type: object
    properties:
      Self:
        type: string
        description: URL para consultar la información del consentimiento.
        minLength: 1
        maxLength: 500
        example: https://apis.com/open-banking/v1/accounts/account-access-consents
  AccountAccessConsentRequest:
    type: object
    required:
      - Data
    properties:
      Data:
        type: object
        required:
          - Permissions
          - AccountOwner
        properties:
          Permissions:
            type: array
            description: >-
              Arreglo que contiene los permisos específicos solicitados por el
              tercero.
            example:
              - ReadAccountBasic
            items:
              type: string
              minLength: 1
              maxLength: 40
          ExpirationDateTime:
            type: string
            format: date-time
            description: >-
              Fecha y hora de expiración para el permiso solicitado. Se
              contemplan 3 vigencias para el consentimiento: durante 3 meses,
              durante 6 meses y durante 1 año. Si no se envía, tomará el valor
              máximo.
          TransactionFromDateTime:
            type: string
            format: date-time
            description: >-
              Fecha desde la cual se solicita listar las transacciones (si el
              permiso solicitado aplica). Si no se envía se solicitarán
              transacciones por el máximo tiempo permitido (90 días) o lo que
              exista en el sistema.
          TransactionToDateTime:
            type: string
            format: date-time
            description: >-
              Fecha hasta la cual se solicita listar las transacciones (si el
              permiso solicitado aplica). Si no se envía se solicitará hasta la
              última transacción disponible.
          AccountOwner:
            $ref: '#/definitions/accountOwner'
  accountOwner:
    type: object
    required:
      - SchemeName
      - Identification
    properties:
      Name:
        type: string
        description: Nombre del cliente autenticado en el tercero
        minLength: 1
        maxLength: 140
        example: Pepito Perez
      SchemeName:
        type: string
        description: Tipo de identificación del cliente autenticado en el tercero.
        minLength: 2
        maxLength: 3
        example: CC
      Identification:
        type: string
        description: Número de identificación del cliente autenticado en el tercero.
        minLength: 1
        maxLength: 35
        example: '7852369429'
  RetrieveAccountAccessConsentResponse:
    type: object
    required:
      - Data
    properties:
      Data:
        type: object
        required:
          - ConsentId
          - Permissions
          - CreationDateTime
          - ExpirationDateTime
          - Status
        properties:
          ConsentId:
            type: string
            description: Identificador creado para el recurso de consentimiento.
            minLength: 1
            maxLength: 128
            example: f236b014ebb845ccal275d638mha5684
          Permissions:
            type: array
            description: >-
              Arreglo que contiene los permisos específicos solicitados por el
              tercero.
            example:
              - ReadAccountBasic
            items:
              type: string
              minLength: 1
              maxLength: 40
          CreationDateTime:
            type: string
            format: date-time
            description: Fecha de creación del recurso de consentimiento.
          ExpirationDateTime:
            type: string
            format: date-time
            description: >-
              Fecha y hora de expiración para el permiso solicitado. Se
              contemplan 3 vigencias para el consentimiento: durante 3 meses,
              durante 6 meses y durante 1 año. Si no se envía, tomará el valor
              máximo.
          TransactionFromDateTime:
            type: string
            format: date-time
            description: >-
              Fecha desde la cual se solicita listar las transacciones (si el
              permiso solicitado aplica). Si no se envía se solicitarán
              transacciones por el máximo tiempo permitido (90 días) o lo que
              exista en el sistema.
            example: '2023-10-26T15:23:00Z'
          TransactionToDateTime:
            type: string
            format: date-time
            description: >-
              Fecha hasta la cual se solicita listar las transacciones (si el
              permiso solicitado aplica). Si no se envía se solicitará hasta la
              última transacción disponible.
            example: '2023-10-26T15:23:00Z'
          Status:
            type: string
            description: >-
              Estado actual del recurso de consentimiento. Al ser un recurso
              nuevo se creará bajo el estado AwaitingAuthorization.
            minLength: 7
            maxLength: 21
            example: AwaitingAuthorization
          StatusUpdateDateTime:
            type: string
            format: date-time
            description: >-
              Fecha en la cual el recurso de consentimiento pasó a tomar el
              estado actual
            example: '2023-10-26T15:23:00Z'
      Links:
        $ref: '#/definitions/Links'
  failure:
    type: object
    description: Mensaje de respuesta cuando ocurre un error.
    required:
      - Errors
    properties:
      Code:
        type: number
        description: >-
          Codigo de estado HTTP (status code) asociado al mensaje de error de la
          respuesta del llamado a la API.
        example: 404
      Message:
        type: string
        description: >-
          Titulo asociado al codigo de estado HTTP (status code) asociado al
          mensaje de error de la respuesta del llamado a la API.
        example: Not Found
      Errors:
        type: array
        description: Lista de errores detectados
        items:
          $ref: '#/definitions/error'
  error:
    type: object
    required:
      - ErrorCode
      - detail
    properties:
      ErrorCode:
        description: An application-specific error code, expressed as a string value.
        type: string
        example: BP404
      Detail:
        description: >-
          A human-readable explanation specific to this occurrence of the
          problem.
        type: string
        example: Requested resource could not be found
schemes:
  - https
consumes:
  - application/vnd.bancolombia.v4+json
host: gw-baas-dev.apps.ambientesbc.lab/public-partner/testing
produces:
  - application/vnd.bancolombia.v4+json
securityDefinitions:
  clientId:
    type: apiKey
    in: header
    name: Client-Id
    x-key-type: client_id
  clientSecret:
    type: apiKey
    in: header
    name: Client-Secret
    x-key-type: client_secret
tags:
  - name: Monitoring
    description: Operaciones para realizar el monitoreo de la API
  - name: Account Access Consents
    description: >-
      Permite a los terceros, en un modelo open banking, solicitar la creación
      de un recurso de consentimiento de acceso a información de cuentas
      Bancolombia, así como consultar el estado del mismo.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  phase: realized
  catalogs:
    Development:
      properties:
        catalogName: development
        profileTls: ''
        endpoint: https://esbdev.bancolombia.corp:3300/ESB/SOAP/Default
    Production:
      properties:
        catalogName: production
        profileTls: ''
        endpoint: https://esbpro.bancolombia.corp:3300/ESB/SOAP/Default
    Testing:
      properties:
        catalogName: testing
        profileTls: ''
        endpoint: https://esbqa.bancolombia.corp:3300/ESB/SOAP/Default
    Sandbox:
      properties:
        catalogName: sandbox
        profileTls: apic-tls-profile-cluster-eks-integracion-sandbox:1.0.0
        endpoint: https://integracion-int-qa.apps.ambientesbc.lab/
  type: rest
x-API-Protocol:
  Protocols: HTTPS
