swagger: '2.0'
info:
  title: Account Information - Balances
  version: 1.0.0
  description: >-
    Habilita a terceros, bajo modelo de Open Banking, consultar los saldos de
    cuentas de depósito previamente autorizadas por el cliente Bancolombia.
  x-ibm-name: account-information-balances
basePath: public-partner/testing/open-banking/v1/deposits
paths:
  /accounts/balances:
    get:
      operationId: CustomerAccountsBalances
      x-api-type: traditional
      summary: Devuelve los saldos de las cuentas de depósitos.
      description: >-
        ### Clasificación de la información: Confidencial

        Devuelve información de los saldos de las cuentas del usuario final que
        se encuentra autenticado.
      parameters:
        - name: authorization
          in: header
          required: true
          type: string
          description: Token de autorización tipo Bearer como lo indica la RFC 6750
        - name: x-fapi-auth-date
          in: header
          required: false
          type: string
          description: >-
            Indica la última vez que el usuario final se autenticó en la
            aplicación del tercero.
        - name: x-fapi-customer-ip-address
          in: header
          required: false
          type: string
          description: >-
            Dirección IP del usuario final que está haciendo uso de la
            aplicación del tercero.
        - name: x-fapi-interaction-id
          in: header
          required: true
          type: string
          description: >-
            Identificador único de transacción que sea común entre el llamado
            del tercero y la respuesta del recurso, para fines de trazabilidad.
        - name: pageNumber
          in: query
          required: false
          type: string
          description: Número de página
        - name: accept
          in: header
          required: false
          type: string
          description: >-
            Indica el formato de mensajería que es aceptado como respuesta de la
            API (application/json)
      responses:
        '200':
          x-success-response: Successfull
          schema:
            $ref: '#/definitions/CustomerAccountsBalancesResponse'
          description: Respuesta exitosa
          x-ibm-languages:
            description:
              en: Successful response.
          headers:
            content-type:
              type: string
              description: >-
                Indica el formato de mensajería que es aceptado como respuesta
                de la API (application/json)
              x-ibm-languages:
                description:
                  en: >-
                    API message format. Example:
                    application/vnd.bancolombia.v4+json.
            x-fapi-interaction-id:
              type: string
              description: >-
                Identificador único de transacción que sea común entre el
                llamado del tercero y la respuesta del recurso, para fines de
                trazabilidad.
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '500':
          $ref: '#/responses/500'
      security:
        - clientSecret: []
          clientId: []
      tags:
        - Balances
  /accounts/{accountIdentification}/balances:
    get:
      operationId: AccountBalances
      x-api-type: traditional
      summary: Devuelve los saldos de una cuenta de depósitos.
      description: >-
        ### Clasificación de la información: Confidencial

        Devuelve información de los saldos de una cuenta específica del usuario
        final que se encuentra autenticado.
      parameters:
        - name: authorization
          in: header
          required: true
          type: string
          description: Token de autorización tipo Bearer como lo indica la RFC 6750.
        - name: x-fapi-auth-date
          in: header
          required: false
          type: string
          description: >-
            Indica la última vez que el usuario final se autenticó en la
            aplicación del tercero/consumidor.
        - name: x-fapi-customer-ip-address
          in: header
          required: false
          type: string
          description: >-
            Dirección IP del usuario final que está haciendo uso de la
            aplicación del tercero/consumidor.
        - name: x-fapi-interaction-id
          in: header
          required: true
          type: string
          description: >-
            Identificador único de transacción que sea común entre el llamado
            del tercero y la respuesta del recurso, para fines de trazabilidad.
        - name: accountIdentification
          in: path
          required: true
          type: string
          description: >-
            Identificador único de la cuenta para la cual se requiere consultar
            los saldos.
        - name: accept
          in: header
          required: false
          type: string
          description: >-
            Indica el formato de mensajería que es aceptado como respuesta de la
            API (application/json)
      responses:
        '200':
          x-success-response: Successfull
          schema:
            $ref: '#/definitions/AccountBalancesResponse'
          description: Respuesta exitosa
          x-ibm-languages:
            description:
              en: Successful response.
          headers:
            content-type:
              type: string
              description: >-
                Indica el formato de mensajería que es aceptado como respuesta
                de la API (application/json)
              x-ibm-languages:
                description:
                  en: >-
                    API message format. Example:
                    application/vnd.bancolombia.v4+json.
            x-fapi-interaction-id:
              type: string
              description: >-
                Identificador único de transacción que sea común entre el
                llamado del tercero y la respuesta del recurso, para fines de
                trazabilidad.
        '401':
          $ref: '#/responses/401'
        '500':
          $ref: '#/responses/500'
      security:
        - clientSecret: []
          clientId: []
      tags:
        - Balances
  /health:
    head:
      operationId: healthOperation
      responses:
        '200':
          description: Respuesta exitosa.
          x-ibm-languages:
            description:
              en: Successful response.
      security:
        - clientId: []
          clientSecret: []
      tags:
        - Monitoring
responses:
  '400':
    schema:
      $ref: '#/definitions/failure'
    description: Error en la solicitud.
    x-ibm-languages:
      description:
        en: Error in the request.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 400
        Message: Bad Resquest
        Errors:
          - ErrorCode: SA404
            Detail: Número de página no proporcionado.
    headers:
      content-type:
        type: string
        description: >-
          Indica el formato de mensajería que es aceptado como respuesta de la
          API (application/json)
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/vnd.bancolombia.v4+json.'
      x-fapi-interaction-id:
        type: string
        description: >-
          Identificador único de transacción que sea común entre el llamado del
          tercero y la respuesta del recurso, para fines de trazabilidad.
  '401':
    schema:
      $ref: '#/definitions/failure'
    description: Credenciales incorrectas.
    x-ibm-languages:
      description:
        en: Incorrect credentials.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 401
        Message: Unauthorized
        Errors:
          - ErrorCode: SA401
            Detail: Consulta no autorizada por el usuario.
    headers:
      content-type:
        type: string
        description: >-
          Indica el formato de mensajería que es aceptado como respuesta de la
          API (application/json)
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/vnd.bancolombia.v4+json.'
      x-fapi-interaction-id:
        type: string
        description: >-
          Identificador único de transacción que sea común entre el llamado del
          tercero y la respuesta del recurso, para fines de trazabilidad.
  '500':
    schema:
      $ref: '#/definitions/failure'
    description: Error interno del servidor.
    x-ibm-languages:
      description:
        en: Internal server error.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 500
        Message: Internal Server Error
        Errors:
          - ErrorCode: SP500
            Detail: Ha ocurrido un error interno controlado en el servidor.
    headers:
      content-type:
        type: string
        description: >-
          Indica el formato de mensajería que es aceptado como respuesta de la
          API (application/json)
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/vnd.bancolombia.v4+json.'
      x-fapi-interaction-id:
        type: string
        description: >-
          Identificador único de transacción que sea común entre el llamado del
          tercero y la respuesta del recurso, para fines de trazabilidad.
definitions:
  MultilateralBalance:
    type: array
    items:
      type: object
      required:
        - Amount
        - Type
      properties:
        Amount:
          type: number
          format: float
          description: Monto del saldo actual, con dos decimales
          minLength: 1
          maxLength: 19
          example: '85000.00'
        Currency:
          type: string
          description: Moneda del saldo actual.
          minLength: 3
          maxLength: 3
          example: COP
        Type:
          type: string
          description: Tipo de saldo.
          minLength: 4
          maxLength: 4
          example: AVLB
  AccountReport:
    type: object
    required:
      - AccountIdentification
      - AccountType
      - AccountName
      - AccountReference
      - AccountStatus
      - MultilateralBalance
    properties:
      AccountIdentification:
        type: string
        description: Identificador único de la cuenta.
        minLength: 1
        maxLength: 40
        example: afebcd15690aefd4
      AccountType:
        type: string
        description: Tipo de cuenta.
        minLength: 4
        maxLength: 4
        example: SVGS
      AccountName:
        type: string
        description: Nombre de la cuenta.
        minLength: 1
        maxLength: 70
        example: Pepito Perez
      AccountReference:
        type: string
        description: Últimos 4 dígitos del número de la cuenta.
        minLength: 4
        maxLength: 4
        example: '5089'
      AccountStatus:
        type: string
        description: Estado actual de la cuenta
        minLength: 1
        maxLength: 10
        example: Enabled
      MultilateralBalance:
        $ref: '#/definitions/MultilateralBalance'
  CustomerAccountsBalancesResponse:
    type: object
    required:
      - Data
    properties:
      Data:
        type: object
        required:
          - AccountReport
        properties:
          AccountReport:
            type: array
            items:
              $ref: '#/definitions/AccountReport'
      Links:
        $ref: '#/definitions/Links'
  Links:
    type: object
    properties:
      Previous:
        type: string
        description: >-
          Enlace que se debe consumir para obtener la página anterior de
          recursos, si no se envía significa que el usuario se encuentra en la
          primera página
        minLength: 1
        maxLength: 500
        example: https://apis.com/open-banking/v1/accounts?pageNumber=1
      Self:
        type: string
        description: Enlace que apunta a la página actual de recursos
        minLength: 1
        maxLength: 500
        example: https://apis.com/open-banking/v1/accounts?pageNumber=2
      Next:
        type: string
        description: >-
          Enlace que se debe consumir para obtener la siguiente página de
          recursos, si no se envía significa que el usuario se encuentra en la
          última página
        minLength: 1
        maxLength: 500
        example: https://apis.com/open-banking/v1/accounts?pageNumber=3
      Last:
        type: string
        description: Enlace que se debe consumir para obtener la última página de recursos
        minLength: 1
        maxLength: 500
        example: https://apis.com/open-banking/v1/accounts?pageNumber=5
  AccountBalancesResponse:
    type: object
    required:
      - Data
    properties:
      Data:
        type: object
        required:
          - AccountReport
        properties:
          AccountReport:
            type: array
            items:
              $ref: '#/definitions/AccountReport'
            maxItems: 1
  failure:
    type: object
    description: Mensaje de respuesta cuando ocurre un error.
    required:
      - Code
      - Message
    properties:
      Code:
        type: number
        description: >-
          Codigo de estado HTTP (status code) asociado al mensaje de error de la
          respuesta del llamado a la API.
        example: 404
      Message:
        type: string
        description: >-
          Titulo asociado al codigo de estado HTTP (status code) asociado al
          mensaje de error de la respuesta del llamado a la API.
        example: Not Found
      Errors:
        type: array
        description: Lista de errores detectados
        items:
          $ref: '#/definitions/error'
  error:
    type: object
    required:
      - ErrorCode
      - Detail
    properties:
      ErrorCode:
        description: An application-specific error code, expressed as a string value.
        type: string
        example: BP404
      Detail:
        description: >-
          A human-readable explanation specific to this occurrence of the
          problem.
        type: string
        example: Requested resource could not be found
schemes:
  - https
consumes:
  - application/vnd.bancolombia.v4+json
host: gw-baas-dev.apps.ambientesbc.lab/public-partner/testing
produces:
  - application/vnd.bancolombia.v4+json
securityDefinitions:
  clientId:
    type: apiKey
    in: header
    name: Client-Id
    x-key-type: client_id
  clientSecret:
    type: apiKey
    in: header
    name: Client-Secret
    x-key-type: client_secret
tags:
  - name: Monitoring
    description: Operaciones para realizar el monitoreo de la API
  - name: Balances
    description: >-
      Permite a los terceros, en un modelo de open banking, consultar la
      información de saldos de cuentas de depósito sobre las cuales el cliente
      Bancolombia ha autorizado acceder.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  phase: realized
  catalogs:
    Development:
      properties:
        catalogName: development
        profileTls: ''
        endpoint: https://esbdev.bancolombia.corp:3300/ESB/SOAP/Default
    Production:
      properties:
        catalogName: production
        profileTls: ''
        endpoint: https://esbpro.bancolombia.corp:3300/ESB/SOAP/Default
    Testing:
      properties:
        catalogName: testing
        profileTls: ''
        endpoint: https://esbqa.bancolombia.corp:3300/ESB/SOAP/Default
    Sandbox:
      properties:
        catalogName: sandbox
        profileTls: apic-tls-profile-cluster-eks-integracion-sandbox:1.0.0
        endpoint: https://integracion-int-qa.apps.ambientesbc.lab/
  type: rest
x-API-Protocol:
  Protocols: HTTPS
