swagger: '2.0'
info:
  title: Account Information - Transactions
  version: 1.0.0
  description: >-
    Habilita a terceros, bajo modelo de Open Banking, consultar los movimientos
    de una cuenta depósito previamente autorizada por el cliente Bancolombia.
  x-ibm-name: account-information-transactions
basePath: public-partner/testing/open-banking/v1/deposits
paths:
  /accounts/{accountIdentification}/transactions:
    get:
      operationId: AccountTransactions
      x-api-type: traditional
      summary: Devuelve los movimientos de una cuenta de depósitos.
      description: >-
        ### Clasificación de la información: Confidencial

        Devuelve información de los movimientos de una cuenta específica del
        usuario final que se encuentra autenticado.
      parameters:
        - name: authorization
          in: header
          required: true
          type: string
          description: Token de autorización tipo Bearer como lo indica la RFC 6750.
        - name: x-fapi-auth-date
          in: header
          required: false
          type: string
          description: >-
            Indica la última vez que el usuario final se autenticó en la
            aplicación del tercero
        - name: x-fapi-customer-ip-address
          in: header
          required: false
          type: string
          description: >-
            Dirección IP del usuario final que está haciendo uso de la
            aplicación del tercero
        - name: x-fapi-interaction-id
          in: header
          required: true
          type: string
          description: >-
            Identificador único de transacción que sea común entre el llamado
            del tercero y la respuesta del recurso, para fines de trazabilidad.
        - name: accountIdentification
          in: path
          required: true
          type: string
          description: >-
            Identificador de la cuenta para la cual se requiere consultar los
            movimientos.
        - name: fromValueDate
          in: query
          required: false
          type: string
          description: >-
            Fecha de aplicación desde la cual se requieren consultar los
            movimientos. Si no se envía, se devolverá desde la primera
            transacción autorizada. Rango máximo de consulta: 3 meses.
        - name: toValueDate
          in: query
          required: false
          type: string
          description: >-
            Fecha de aplicación hasta la cual se requieren consultar los
            movimientos. Si no se envía, se devolverá hasta la última
            transacción autorizada. Rango máximo de consulta: 3 meses.
        - name: pageNumber
          in: query
          required: false
          type: string
          description: Número de página
        - name: accept
          in: header
          required: false
          type: string
          description: >-
            Indica el formato de mensajería que es aceptado como respuesta de la
            API (application/json)
      responses:
        '200':
          x-success-response: Successfull
          schema:
            $ref: '#/definitions/AccountTransactionsResponse'
          description: Respuesta exitosa
          x-ibm-languages:
            description:
              en: Successful response.
          headers:
            content-type:
              type: string
              description: >-
                Indica el formato de mensajería que es aceptado como respuesta
                de la API (application/json)
              x-ibm-languages:
                description:
                  en: >-
                    API message format. Example:
                    application/vnd.bancolombia.v4+json.
            x-fapi-interaction-id:
              type: string
              description: >-
                Identificador único de transacción que sea común entre el
                llamado del tercero y la respuesta del recurso, para fines de
                trazabilidad.
        '400':
          $ref: '#/responses/400'
        '401':
          $ref: '#/responses/401'
        '500':
          $ref: '#/responses/500'
      security:
        - clientSecret: []
          clientId: []
      tags:
        - Transactions
  /health:
    head:
      operationId: healthOperation
      responses:
        '200':
          description: Respuesta exitosa.
          x-ibm-languages:
            description:
              en: Successful response.
      security:
        - clientId: []
          clientSecret: []
      tags:
        - Monitoring
responses:
  '400':
    schema:
      $ref: '#/definitions/failure'
    description: Error en la solicitud.
    x-ibm-languages:
      description:
        en: Error in the request.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 400
        Message: Bad Resquest
        Errors:
          - ErrorCode: SA400
            Detail: Identificador de cuenta no proporcionado
    headers:
      content-type:
        type: string
        description: >-
          Indica el formato de mensajería que es aceptado como respuesta de la
          API (application/json)
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/vnd.bancolombia.v4+json.'
      x-fapi-interaction-id:
        type: string
        description: >-
          Identificador único de transacción que sea común entre el llamado del
          tercero y la respuesta del recurso, para fines de trazabilidad.
  '401':
    schema:
      $ref: '#/definitions/failure'
    description: Petición inválida.
    x-ibm-languages:
      description:
        en: Incorrect Authorization.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 401
        Message: Unauthorized
        Errors:
          - ErrorCode: SA401
            Detail: Consulta no autorizada por el usuario.
    headers:
      content-type:
        type: string
        description: >-
          Indica el formato de mensajería que es aceptado como respuesta de la
          API (application/json)
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/vnd.bancolombia.v4+json.'
      x-fapi-interaction-id:
        type: string
        description: >-
          Identificador único de transacción que sea común entre el llamado del
          tercero y la respuesta del recurso, para fines de trazabilidad.
  '500':
    schema:
      $ref: '#/definitions/failure'
    description: Error interno del servidor.
    x-ibm-languages:
      description:
        en: Internal server error.
    examples:
      application/vnd.bancolombia.v4+json:
        Code: 500
        Message: Internal Server Error
        Errors:
          - ErrorCode: SP500
            Detail: Ha ocurrido un error interno controlado en el servidor.
    headers:
      content-type:
        type: string
        description: >-
          Indica el formato de mensajería que es aceptado como respuesta de la
          API (application/json)
        x-ibm-languages:
          description:
            en: 'API message format. Example: application/vnd.bancolombia.v4+json.'
      x-fapi-interaction-id:
        type: string
        description: >-
          Identificador único de transacción que sea común entre el llamado del
          tercero y la respuesta del recurso, para fines de trazabilidad.
definitions:
  CreditorAgent:
    type: object
    properties:
      Name:
        type: string
        description: >-
          Nombre de la entidad financiera que sirve la cuenta destino de la
          transacción.
        minLength: 1
        maxLength: 140
        example: Davivienda
      FinancialInstitutionIdentification:
        type: string
        description: >-
          Código asignado por BANREP para la entidad financiera que sirve la
          cuenta destino de la transacción
        minLength: 1
        maxLength: 4
        example: '0007'
  AccountTransactionsResponse:
    type: object
    required:
      - Data
    properties:
      Data:
        type: object
        required:
          - TransactionReport
        properties:
          TransactionReport:
            $ref: '#/definitions/TransactionReport'
      Links:
        $ref: '#/definitions/Links'
  Links:
    type: object
    properties:
      Previous:
        type: string
        description: >-
          Enlace que se debe consumir para obtener la página anterior de
          recursos, si no se envía significa que el usuario se encuentra en la
          primera página
        minLength: 1
        maxLength: 500
        example: https://apis.com/open-banking/v1/accounts?pageNumber=1
      Self:
        type: string
        description: Enlace que apunta a la página actual de recursos
        minLength: 1
        maxLength: 500
        example: https://apis.com/open-banking/v1/accounts?pageNumber=2
      Next:
        type: string
        description: >-
          Enlace que se debe consumir para obtener la siguiente página de
          recursos, si no se envía significa que el usuario se encuentra en la
          última página
        minLength: 1
        maxLength: 500
        example: https://apis.com/open-banking/v1/accounts?pageNumber=3
      Last:
        type: string
        description: Enlace que se debe consumir para obtener la última página de recursos
        minLength: 1
        maxLength: 500
        example: https://apis.com/open-banking/v1/accounts?pageNumber=5
  TransactionReport:
    type: array
    items:
      type: object
      required:
        - TransactionIdentification
        - TransactionInformation
        - CreditDebitIndicator
        - ValueDateTime
        - InstructedAmount
      properties:
        TransactionIdentification:
          type: string
          description: Identificador único generado para la transacción
          minLength: 1
          maxLength: 210
          example: '00001'
        TransactionInformation:
          type: string
          description: Descripción de la transacción
          minLength: 1
          maxLength: 500
          example: Compra Comercio A
        TransactionReference:
          type: string
          description: Referencia adicional de la transacción
          minLength: 1
          maxLength: 500
          example: Ref 2
        CreditDebitIndicator:
          type: string
          description: >-
            Indica si la transacción fue una salida (DBIT) o entrada (CRDT) de
            dinero
          enum:
            - DBIT
            - CRDT
        RequestedExecutionDate:
          type: string
          format: date-time
          description: Fecha y hora del movimiento.
          example: '2023-10-26T15:23:00Z'
        ValueDateTime:
          type: string
          format: date-time
          description: Fecha y hora de aplicación del movimiento
          example: '2023-10-26T15:38:00Z'
        CreditorAgent:
          $ref: '#/definitions/CreditorAgent'
        Status:
          type: string
          description: Estado actual de la transacción.
          minLength: 4
          maxLength: 4
          example: STLD
        InstructedAmount:
          $ref: '#/definitions/InstructedAmount'
        Creditor:
          $ref: '#/definitions/Creditor'
  Creditor:
    type: object
    properties:
      Name:
        type: string
        description: Nombre del comercio destino de la transacción
        minLength: 1
        maxLength: 140
        example: Comercio A
      RegistrationIdentification:
        type: string
        description: Código único del comercio destino de la transacción
        minLength: 1
        maxLength: 35
        example: '101020'
  InstructedAmount:
    type: object
    required:
      - Amount
    properties:
      Amount:
        type: number
        format: float
        description: Monto de la transacción. Debe contener dos decimales
        minLength: 1
        maxLength: 19
        example: '85000.00'
      Currency:
        type: string
        description: Moneda en la cual se ejecutó la transacción
        minLength: 3
        maxLength: 3
        example: COP
  failure:
    type: object
    description: Mensaje de respuesta cuando ocurre un error.
    required:
      - Code
      - Message
    properties:
      Code:
        type: number
        description: >-
          Codigo de estado HTTP (status code) asociado al mensaje de error de la
          respuesta del llamado a la API.
        example: 404
      Message:
        type: string
        description: >-
          Titulo asociado al codigo de estado HTTP (status code) asociado al
          mensaje de error de la respuesta del llamado a la API.
        example: Not Found
      Errors:
        type: array
        description: Lista de errores detectados
        items:
          $ref: '#/definitions/error'
  error:
    type: object
    required:
      - ErrorCode
      - Detail
    properties:
      ErrorCode:
        description: An application-specific error code, expressed as a string value.
        type: string
        example: BP404
      Detail:
        description: >-
          A human-readable explanation specific to this occurrence of the
          problem.
        type: string
        example: Requested resource could not be found
schemes:
  - https
consumes:
  - application/vnd.bancolombia.v4+json
host: gw-baas-dev.apps.ambientesbc.lab/public-partner/testing
produces:
  - application/vnd.bancolombia.v4+json
securityDefinitions:
  clientId:
    type: apiKey
    in: header
    name: Client-Id
    x-key-type: client_id
  clientSecret:
    type: apiKey
    in: header
    name: Client-Secret
    x-key-type: client_secret
tags:
  - name: Monitoring
    description: Operaciones para realizar el monitoreo de la API
  - name: Transactions
    description: >-
      Permite a los terceros, en un modelo de open banking, consultar los
      movimientos de una cuenta de depósito sobre la cual el cliente Bancolombia
      ha autorizado acceder
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  phase: realized
  catalogs:
    Development:
      properties:
        catalogName: development
        profileTls: ''
        endpoint: https://esbdev.bancolombia.corp:3300/ESB/SOAP/Default
    Production:
      properties:
        catalogName: production
        profileTls: ''
        endpoint: https://esbpro.bancolombia.corp:3300/ESB/SOAP/Default
    Testing:
      properties:
        catalogName: testing
        profileTls: ''
        endpoint: https://esbqa.bancolombia.corp:3300/ESB/SOAP/Default
    Sandbox:
      properties:
        catalogName: sandbox
        profileTls: apic-tls-profile-cluster-eks-integracion-sandbox:1.0.0
        endpoint: https://integracion-int-qa.apps.ambientesbc.lab/
  type: rest
x-API-Protocol:
  Protocols: HTTPS
